function info = ensureDefaultMarketplace()
%ENSUREDEFAULTMARKETPLACE Register the built-in marketplace when it is absent.

    defaultMarketplace = interactiveMissions.internal.defaultMarketplace();
    records = interactiveMissions.internal.marketplaceRegistry("get");
    recordIndex = find(strcmpi(string({records.Id}), defaultMarketplace.Id), 1);
    if ~isempty(recordIndex)
        record = records(recordIndex);
        isConfigured = logical(record.IsDefault) && ...
            strcmpi(string(record.RemoteUrl), defaultMarketplace.SourceUrl) && ...
            string(record.ReferenceType) == defaultMarketplace.ReferenceType && ...
            string(record.ReferenceName) == defaultMarketplace.ReferenceName;
        if isConfigured
            info = record;
            return
        end
    end

    info = interactiveMissions.registerMarketplace( ...
        SourceUrl=defaultMarketplace.SourceUrl, ...
        ReferenceType=defaultMarketplace.ReferenceType, ...
        ReferenceName=defaultMarketplace.ReferenceName, ...
        ReplaceExisting=~isempty(recordIndex), ...
        IsDefault=true);
end
