function status = prerequisites()
%PREREQUISITES Report MATLAB-side readiness for Interactive Missions.

    status = [
        makeStatus( ...
            "MATLAB MCP Server", ...
            "mcp", ...
            exist("shareMATLABSession", "file") == 2, ...
            "Lets your agent inspect and interact with the active MATLAB session.", ...
            "https://github.com/mathworks/matlab-mcp-server")
        makeStatus( ...
            "Agentic Toolboxes", ...
            "agentic-toolboxes", ...
            exist("satk_initialize", "file") == 2, ...
            "Adds MATLAB and Simulink agent tooling used by richer missions.", ...
            "https://github.com/mathworks/matlab-agentic-toolkit")
        makeStatus( ...
            "Terminal-in-MATLAB", ...
            "terminal-in-matlab", ...
            exist("terminal", "file") == 2, ...
            "Provides a terminal inside MATLAB so learners can start agents from the prepared work folder.", ...
            "https://www.mathworks.com/matlabcentral/fileexchange/")
        ];
end

function status = makeStatus(name, identifier, installed, details, link)
    if installed
        readiness = "pass";
    else
        readiness = "warn";
    end

    status = struct( ...
        "Name", string(name), ...
        "Identifier", string(identifier), ...
        "Status", string(readiness), ...
        "Installed", logical(installed), ...
        "Enabled", logical(installed), ...
        "Details", string(details), ...
        "Link", string(link) ...
        );
end
