classdef DocsAndSkillsTest < matlab.unittest.TestCase
    %DOCSANDSKILLSTEST Verify documentation and skill packaging contracts.

    properties (TestParameter)
        Root = {interactiveMissionsSmoke.defaultRoot()}
    end

    methods (Test)
        function validatesReadme(testCase, Root)
            root = string(Root);
            readmeText = fileread(fullfile(root, "README.md"));

            for phrase = ["MATLAB toolbox", "InteractiveMissions.mltbx", "buildtool package", ...
                    "safe workspace", ...
                    "Start Mission", "Resume", "Documents/MATLAB/Interactive-Missions", ...
                    "<mission-name>", "$mission-tutoring", ...
                    "marketplace", ".interactive-missions/progress.json", ...
                    "GitHub Copilot CLI"]
                testCase.verifyTrue(contains(readmeText, phrase), ...
                    "README must mention '" + phrase + "'");
            end
            for phrase = ["Import Mission Pack", "mission pack ZIP", "user mission library"]
                testCase.verifyFalse(contains(readmeText, phrase), ...
                    "README must not mention old sharing surface '" + phrase + "'");
            end
        end

        function validatesMissionContract(testCase, Root)
            root = string(Root);
            referencesRoot = fullfile(root, "src", "author-skills", "references");
            contractText = fileread(fullfile(referencesRoot, "mission-contract.md"));

            testCase.verifyTrue(contains(contractText, "marketplace/missions"), ...
                "mission contract must point at marketplace/missions");
            testCase.verifyTrue(contains(contractText, ".interactive-missions/progress.json"), ...
                "mission contract must describe workspace-local progress");
            progressContract = fileread(fullfile(referencesRoot, "progress-contract.md"));
            for phrase = ["learnerName", "hintCounts", "updatedAt", "notes"]
                testCase.verifyTrue(contains(progressContract, phrase), ...
                    "progress contract must mention " + phrase);
            end
            testCase.verifyTrue(isfile(fullfile(referencesRoot, "platform-qualification.md")), ...
                "shared platform qualification document is missing");
            for contractName = ["mission-contract.md", "progress-contract.md", "platform-qualification.md"]
                testCase.verifyFalse(isfile(fullfile(root, "docs", contractName)), ...
                    "former app Help contract must not exist: docs/" + contractName);
            end
            testCase.verifyTrue(isfile(fullfile(root, "docs", "agent-support-matrix.json")), ...
                "platform qualification matrix is missing");
        end

        function validatesAppDocumentation(testCase, Root)
            root = string(Root);
            documentationRoot = fullfile(root, "docs");
            appClassPath = fullfile(root, "src", "+interactiveMissions", "+internal", ...
                "MissionBrowserApp.m");
            appClassText = string(fileread(appClassPath));
            appScriptText = string(fileread(fullfile(root, "src", "app", "app.js")));
            appStyleText = string(fileread(fullfile(root, "src", "app", "styles.css")));

            testCase.verifyTrue(isfile(fullfile(documentationRoot, "1-index.md")), ...
                "app documentation index is missing from docs");
            testCase.verifyTrue(isfile(fullfile(root, "src", "docs", "learner-faq.md")), ...
                "learner FAQ is missing from src/docs");
            testCase.verifyTrue(contains(appClassText, ...
                'fullfile(interactiveMissions.internal.toolboxRoot(), "docs")'), ...
                "app documentation must load pages from docs");
            testCase.verifyTrue(contains(appClassText, ...
                'state.LearnerFaq = app.learnerFaqForUi();') && ...
                contains(appClassText, ...
                'fullfile(interactiveMissions.internal.toolboxRoot(), "src", "docs", "learner-faq.md")'), ...
                "app must load learner FAQ from src/docs/learner-faq.md");
            testCase.verifyFalse(contains(appClassText, ...
                'fullfile(interactiveMissions.internal.toolboxRoot(), "src", "doc")'), ...
                "app documentation must not load pages from src/doc");
            testCase.verifyTrue(contains(appScriptText, "function decodeHtmlEntities"), ...
                "app documentation renderer must define an HTML entity decoder");
            testCase.verifyTrue(contains(appScriptText, ...
                "let markdown = decodeHtmlEntities(text)") && ...
                contains(appScriptText, "let html = escapeHtml(markdown)") && ...
                contains(appScriptText, "function saveToken(html)"), ...
                "app documentation renderer must decode entities before escaping text");
            testCase.verifyTrue(contains(appScriptText, ...
                "decodeHtmlEntities(firstLine(page.Title || page.FileName))"), ...
                "app documentation navigation must decode page labels");
            testCase.verifyTrue(contains(appScriptText, "return decodeHtmlEntities(plainText)"), ...
                "app documentation headings must decode entity text");
            testCase.verifyTrue(contains(appScriptText, 'if (/^>\s?/.test(trimmed))') && ...
                contains(appScriptText, 'element("blockquote", "")') && ...
                contains(appScriptText, "inlineMarkdown(quoteLines.join"), ...
                "app documentation renderer must render Markdown blockquotes");
            testCase.verifyTrue(contains(appStyleText, ".docs-content blockquote") && ...
                contains(appStyleText, "padding: 0 0 0 1.5em") && ...
                contains(appStyleText, "border-left: 2px solid #0076a8") && ...
                contains(appStyleText, "color: #000000"), ...
                "app documentation blockquotes must use the app visual style");
            testCase.verifyTrue(contains(appScriptText, "function markdownTableDefinition") && ...
                contains(appScriptText, "function markdownTableRow") && ...
                contains(appScriptText, '/^:?-{3,}:?$/') && ...
                contains(appScriptText, 'element("table", "docs-table")') && ...
                contains(appScriptText, 'headerCell.scope = "col"') && ...
                contains(appScriptText, 'element("thead", "")') && ...
                contains(appScriptText, 'element("tbody", "")'), ...
                "app documentation renderer must render valid pipe tables semantically");
            testCase.verifyTrue(contains(appScriptText, 'element("div", "docs-table-wrap")') && ...
                contains(appScriptText, "headerCell.innerHTML = inlineMarkdown(header, contextFileName)") && ...
                contains(appScriptText, "bodyCell.innerHTML = inlineMarkdown(cellText, contextFileName)") && ...
                contains(appScriptText, 'markdown = markdown.replace(/`([^`]+)`/') && ...
                contains(appScriptText, 'markdown = markdown.replace(/\[([^\]]+)\]\(([^)]+)\)/'), ...
                "app documentation tables must support inline Markdown without formatting code spans or link destinations");
            testCase.verifyTrue(contains(appStyleText, ".docs-table-wrap") && ...
                contains(appStyleText, "overflow-x: auto") && ...
                contains(appStyleText, ".docs-table th,") && ...
                contains(appStyleText, "background: #f2f2f2"), ...
                "app documentation tables must be responsive and match the Help visual style");
            testCase.verifyTrue(contains(appScriptText, "function documentationNavigation") && ...
                contains(appScriptText, 'fileName.match(/^(\d+)-/)'), ...
                "app documentation navigation must classify numbered walkthrough pages by filename");
            testCase.verifyTrue(contains(appScriptText, "Number.parseInt(walkthroughMatch[1], 10)") && ...
                contains(appScriptText, "left.Order - right.Order"), ...
                "app documentation navigation must sort walkthrough pages numerically");
            testCase.verifyTrue(contains(appScriptText, "referencePages.sort(function compareReference"), ...
                "app documentation navigation must sort reference pages by filename");
            walkthroughPosition = strfind(appScriptText, ...
                "renderDocumentationPageButtons(pageList, navigation.Walkthrough)");
            referencePosition = strfind(appScriptText, ...
                "renderDocumentationPageButtons(pageList, navigation.Reference)");
            testCase.verifyTrue(~contains(appScriptText, 'fileName.toLowerCase() === "author-faq.md"') && ...
                isscalar(walkthroughPosition) && isscalar(referencePosition) && ...
                walkthroughPosition < referencePosition, ...
                "app documentation navigation must classify Author FAQ with Reference pages");
            testCase.verifyTrue(contains(appScriptText, 'appendDocumentationSectionLabel(pageList, "Walkthrough")') && ...
                contains(appScriptText, 'appendDocumentationSectionLabel(pageList, "Reference")') && ...
                contains(appScriptText, "docs-section-label"), ...
                "app documentation navigation must render Walkthrough and Reference section labels");
            testCase.verifyTrue(contains(appScriptText, ...
                'getElementById("documentationContent").addEventListener("click", handleMarkdownContentClick)') && ...
                contains(appScriptText, 'event.target.closest("a")'), ...
                "app documentation links must use delegated Help-content click handling");
            testCase.verifyTrue(contains(appScriptText, 'function renderLearnerFaq') && ...
                contains(appScriptText, 'renderMarkdown(state.LearnerFaq.Markdown || "", learnerFaqFileName())') && ...
                contains(appScriptText, 'renderLearnerFaqHeadings(renderResult.Headings)') && ...
                contains(appScriptText, ...
                'getElementById("learnerFaqContent").addEventListener("click", handleMarkdownContentClick)'), ...
                "learner FAQ must use the shared Markdown renderer, heading navigation, and link handling");
            testCase.verifyTrue(contains(appScriptText, "function documentationFileName") && ...
                contains(appScriptText, "Documentation page not found:"), ...
                "app documentation links must normalize page names and report missing pages");
            testCase.verifyTrue(contains(appScriptText, 'send("openDocumentationUrl", { Url:') && ...
                contains(appScriptText, "IsWeb: true") && ...
                contains(appScriptText, "return safeLabel;"), ...
                "app documentation links must route HTTP(S) URLs through MATLAB and render relative non-Markdown files as text");
            testCase.verifyTrue(contains(appClassText, 'case "openDocumentationUrl"') && ...
                contains(appClassText, 'startsWith(url, ["http://", "https://"], IgnoreCase=true)') && ...
                contains(appClassText, 'web(url, "-browser");'), ...
                "app must validate HTTP(S) documentation URLs before opening the system browser");
        end

        function validatesLearnerTutorSkill(testCase, Root)
            root = string(Root);
            tutorText = fileread(fullfile(root, "src", "skills", "mission-tutoring", "SKILL.md"));

            for phrase = ["safe workspace", "content/mission.yaml", ...
                    ".interactive-missions/progress.json", "allow_agent_edits", "allowAgentEdits"]
                testCase.verifyTrue(contains(tutorText, phrase), ...
                    "tutor skill must mention '" + phrase + "'");
            end
            testCase.verifyFalse(contains(lower(tutorText), "plugin root"), ...
                "tutor skill must not reference plugin root paths");
            for phrase = ["Let the learner perform the work.", ...
                    "primary source of learner-facing task help", ...
                    "complete recipe"]
                testCase.verifyTrue(contains(tutorText, phrase), ...
                    "tutor skill must specify '" + phrase + "'");
            end

            skillRoot = fullfile(root, "src", "skills", "mission-tutoring");
            organizerPath = fullfile(skillRoot, "references", "advance-organizer.md");
            statusPath = fullfile(skillRoot, "references", "status-reporting.md");
            startupText = fileread(fullfile(skillRoot, "references", "session-startup.md"));
            resourcesText = fileread(fullfile(skillRoot, "references", "mission-resources.md"));
            taskLoopText = fileread(fullfile(skillRoot, "references", "task-loop.md"));
            endingText = fileread(fullfile(skillRoot, "references", "progress-and-ending.md"));
            testCase.verifyTrue(isfile(organizerPath), ...
                "tutor skill must include a dedicated advance organizer reference");
            testCase.verifyTrue(isfile(statusPath), ...
                "tutor skill must include a status-reporting reference");
            organizerText = fileread(organizerPath);
            statusText = fileread(statusPath);
            for phrase = ["3-5 concise sentences", "only the mission `title` and `objective`", ...
                    "explicit prerequisite or assumed-prior-knowledge statements", ...
                    "include that prerequisite information in the opening summary", ...
                    "outside facts, hints, completion checks, commands, parameter values, mechanical steps, or solutions", ...
                    "exactly one short, narrowly scoped prediction question", ...
                    "without evaluating, grading, correcting, or revealing the answer"]
                testCase.verifyTrue(contains(organizerText, phrase), ...
                    "advance organizer must specify '" + phrase + "'");
            end
            for phrase = ["provide a display name or use a generated alliterative MATLAB/Simulink-animal name", ...
                    "tracked missions need a display name", "do not present the organizer or Task 1", ...
                    "Task 1 and no mission tasks are complete", "Wait for the learner's prediction response", ...
                    "resuming at Task 2 or later, skip the organizer"]
                testCase.verifyTrue(contains(startupText, phrase), ...
                    "session startup must specify '" + phrase + "'");
            end
            testCase.verifyFalse(contains(startupText, "or no name"), ...
                "tracked startup must not offer a no-name option");
            testCase.verifyTrue(contains(taskLoopText, "prediction response is not a task attempt"), ...
                "task loop must exclude the organizer prediction from task attempts");
            testCase.verifyTrue(contains(tutorText, "mcpTmp_"), ...
                "tutor skill must require the mcpTmp_ temporary-variable prefix");
            testCase.verifyTrue(contains(tutorText, ...
                "Prefer direct expressions and `fprintf` for MATLAB MCP inspection"), ...
                "tutor skill must prefer inspections without temporary variables");
            testCase.verifyTrue(contains(taskLoopText, ...
                "mcpTmpNames = who(""mcpTmp_*"");"), ...
                "task loop must identify mcpTmp_ temporary variables for cleanup");
            testCase.verifyTrue(contains(taskLoopText, "clear(mcpTmpNames{:})"), ...
                "task loop must clean up only identified mcpTmp_ temporary variables");
            testCase.verifyFalse(contains(taskLoopText, "evalin("), ...
                "task loop must not clear a different MATLAB workspace");
            for phrase = ["identify the smallest unmet part", ...
                    "Use the active task's ordered `hints` list as the authored hint ladder.", ...
                    "directional, specific, then direct", ...
                    "Skip a hint when the learner's current work already addresses its target.", ...
                    "Present exactly one selected YAML hint.", ...
                    "task-effort baseline in session memory", ...
                    "Count task-relevant effort only when product inspection shows a relevant change or partial result", ...
                    "Verbal claims, unrelated changes, repeated requests, and anger do not count as effort.", ...
                    "If the state could instead be setup output, prior completed-task state, or another ambiguous source", ...
                    "exactly one eligible authored hint and encourage the learner to try it", ...
                    "If no eligible hint remains before effort", ...
                    "Anger never bypasses the effort requirement.", ...
                    "Rescue is permitted only after task-relevant effort is observed.", ...
                    "the learner attempted prior guidance and still needs direct help", ...
                    "the remaining eligible authored hints do not address the observed blocker", ...
                    "the applicable authored hints are exhausted", ...
                    "If required product inspection fails or cannot establish effort", ...
                    "Tell me what to do", ...
                    "Repeated requests without a task-relevant change", ...
                    "Exhausted hints without effort", ...
                    "Anger without effort", ...
                    "Observed partial work followed by a direct request", ...
                    "Resumed partial work counts as effort", ...
                    "Re-inspect before every rejection", ...
                    "after the learner disputes an assessment", ...
                    "After the learner reports applying the recipe, re-inspect before assessing completion."]
                testCase.verifyTrue(contains(taskLoopText, phrase), ...
                    "task loop must specify '" + phrase + "'");
            end
            for phrase = ["one or two short, programmatic lines", ...
                    "without first-person narration, future plans, or explanations of internal reasoning", ...
                    "Send a status report as its own message", ...
                    "Reading mission...", "Current state: Mission not started.", ...
                    "MATLAB MCP Server and required tools are available."]
                testCase.verifyTrue(contains(statusText, phrase), ...
                    "status reporting must specify '" + phrase + "'");
            end
            testCase.verifyTrue(contains(tutorText, "status-reporting.md"), ...
                "tutor skill must load the status-reporting reference");
            for lifecycleText = {startupText, resourcesText, taskLoopText, endingText}
                testCase.verifyTrue(contains(lifecycleText, "status-reporting.md"), ...
                    "each mission lifecycle reference must load the status-reporting contract");
            end
        end

        function validatesContinuousAndDiscreteTimeSineWaveContract(testCase, Root)
            root = string(Root);
            missionPath = fullfile(root, "marketplace", "missions", ...
                "continuous-and-discrete-time", "mission.yaml");
            text = string(fileread(missionPath));
            testCase.verifyNotEmpty(regexp(text, '(?m)^version:\s*"1\.0\.1"\s*$', "once"), ...
                "Continuous and Discrete Time mission must increment to version 1.0.1");
            [taskStarts, taskEnds, taskTokens] = regexp(text, '(?m)^  - id:\s*"?(t\d{2})"?', ...
                "start", "end", "tokens");
            taskIds = string(cellfun(@(item) item{1}, taskTokens, UniformOutput=false));
            expectedPhrases = {
                "t01", ["Sine Wave block configured for continuous-time", "Sine Wave source", "continuous-time output"]
                "t02", ["same Sine Wave block", "positive finite sample interval", "Sine Wave source"]
                "t03", ["Sine Wave source to continuous-time output", "continuous-time Sine Wave source", "Sine Wave is continuous"]
                "t04", ["continuous Sine Wave output", "sampled signal derived from that Sine Wave", "continuous Sine Wave"]
                };

            for rowIndex = 1:size(expectedPhrases, 1)
                taskIndex = find(taskIds == expectedPhrases{rowIndex, 1}, 1);
                testCase.assertNotEmpty(taskIndex, "missing required mission task");
                blockText = missionTaskBlockText(text, taskStarts, taskEnds, taskIndex);
                for phrase = expectedPhrases{rowIndex, 2}
                    testCase.verifyTrue(contains(blockText, phrase), ...
                        taskIds(taskIndex) + " must consistently require a Sine Wave source: " + phrase);
                end
            end

            taskOneText = lower(missionTaskBlockText(text, taskStarts, taskEnds, 1));
            for forbiddenPhrase = ["any continuously varying signal source", "equivalent signal-producing subsystem"]
                testCase.verifyFalse(contains(taskOneText, forbiddenPhrase), ...
                    "t01 must not accept an alternate source: " + forbiddenPhrase);
            end
        end

        function validatesAuthorSkills(testCase, Root)
            root = string(Root);
            packagedAuthorSkills = fullfile(root, "src", "author-skills");
            expectedAuthorSkills = ["create-tutor-mission", "qa-mission", "maintain-missions"];
            for contractName = ["mission-contract.md", "progress-contract.md", "platform-qualification.md"]
                testCase.verifyTrue(isfile(fullfile(packagedAuthorSkills, "references", contractName)), ...
                    "shared author reference is missing: " + contractName);
            end

            for skillName = expectedAuthorSkills
                skillPath = fullfile(packagedAuthorSkills, skillName, "SKILL.md");
                testCase.verifyTrue(isfile(skillPath), "missing author skill: " + skillName);
                packagedSkillText = fileread(skillPath);
                testCase.verifyTrue(contains(packagedSkillText, "../references/"), ...
                    skillName + " must reference shared author contracts");
            end
        end

        function validatesPackagedSkills(testCase, Root)
            root = string(Root);
            packagedSkillFiles = dir(fullfile(root, "src", "skills", "*", "SKILL.md"));
            packagedSkillNames = strings(numel(packagedSkillFiles), 1);

            for fileIndex = 1:numel(packagedSkillFiles)
                packagedSkillNames(fileIndex) = parentName(packagedSkillFiles(fileIndex).folder);
            end

            testCase.verifyEqual(sort(packagedSkillNames(:)), "mission-tutoring", ...
                "src/skills must ship only learner tutor skill");
        end

        function validatesAppInformationArchitecture(testCase, Root)
            root = string(Root);
            htmlText = fileread(fullfile(root, "src", "app", "index.html"));
            scriptText = fileread(fullfile(root, "src", "app", "app.js"));
            styleText = fileread(fullfile(root, "src", "app", "styles.css"));
            appClassText = fileread(fullfile(root, "src", "+interactiveMissions", "+internal", "MissionBrowserApp.m"));
            combinedText = string(htmlText) + string(scriptText);
            appImplementationText = combinedText + string(styleText) + string(appClassText);

            testCase.verifyFalse(contains(htmlText, 'data-view="progress"'), ...
                "app must not expose a standalone Progress tab");
            testCase.verifyTrue(contains(scriptText, "indexedResumeSession"), ...
                "resume modal must use backend-selected session index before filtering");
            testCase.verifyTrue(contains(scriptText, "truthyValue(session.IsResumable)"), ...
                "resume modal must normalize MATLAB logical values");
            for phrase = ["Practice", "Start Mission", "Resume", "Authoring Help", "Learner FAQ", "Settings", ...
                    "Agentic client", "Codex", "GitHub Copilot in VS Code", "GitHub Copilot CLI"]
                testCase.verifyTrue(contains(htmlText, phrase) || contains(scriptText, phrase), ...
                    "app UI must include " + phrase);
            end
            missionsTab = strfind(htmlText, 'data-view="missions"');
            faqTab = strfind(htmlText, 'data-view="learner-faq"');
            helpTab = strfind(htmlText, 'data-view="documentation"');
            testCase.verifyTrue(isscalar(missionsTab) && isscalar(faqTab) && isscalar(helpTab) && ...
                missionsTab < faqTab && faqTab < helpTab, ...
                "Learner FAQ tab must appear between Missions and Authoring Help");
            for phrase = ["Import Mission Pack", "Destination user mission library", "Export", "createDraftMetadata"]
                testCase.verifyFalse(contains(combinedText, phrase), ...
                    "app UI must not expose old authoring/import surface " + phrase);
            end
            testCase.verifyTrue(contains(htmlText, 'id="documentationView"') && contains(scriptText, "renderMarkdown"), ...
                "app must include rendered documentation navigation");
            testCase.verifyTrue(contains(htmlText, 'id="learnerFaqView"') && ...
                contains(htmlText, 'id="learnerFaqContent"') && ...
                contains(htmlText, 'id="learnerFaqHeadingList"'), ...
                "app must include a dedicated learner FAQ view and containers");
            testCase.verifyTrue(contains(scriptText, 'replace(/-([a-z])/g') && ...
                contains(scriptText, 'view.id === viewName + "View" || view.id === normalizedViewName + "View"'), ...
                "app tab switching must support hyphenated view names such as Learner FAQ");
            testCase.verifyFalse(contains(lower(appImplementationText), "environment"), ...
                "app implementation must not reference the removed Environment settings panel");
            testCase.verifyTrue(contains(htmlText, '<span id="promptStep3Text"') && ...
                contains(htmlText, '<span id="promptStep4Text"'), ...
                "launch steps 3 and 4 must render as text");
            testCase.verifyTrue(contains(scriptText, "isCdCommand"), ...
                "launch command code box must be limited to terminal commands");
            testCase.verifyFalse(contains(htmlText, "Full launch context"), ...
                "launch modal must not expose full launch context");
            testCase.verifyFalse(contains(combinedText, "launchUsernameInput"), ...
                "Start Mission must not ask for a username in the app");
            testCase.verifyFalse(contains(appImplementationText, "UserProfile") || ...
                contains(appImplementationText, "IsCurrentUser") || ...
                contains(appImplementationText, "state.Identity") || ...
                contains(appImplementationText, "identityUsername"), ...
                "app must not retain profile identity state");
            testCase.verifyTrue(contains(scriptText, "Awaiting learner name") || ...
                contains(appClassText, "Awaiting learner name"), ...
                "app must label unnamed unstarted sessions neutrally");
            testCase.verifyTrue(contains(scriptText, 'launchAgentClientSelect").value = ""'), ...
                "launch modal must require an intentional agent client selection");
            testCase.verifyTrue(contains(scriptText, "Choose an agentic client."), ...
                "launch modal must explain when the agent client is missing");
            testCase.verifyTrue(contains(scriptText, "updateLaunchContinueState"), ...
                "launch modal must disable Continue until required inputs are filled");
            testCase.verifyTrue(contains(scriptText, "unregisterMarketplace") && ...
                contains(htmlText, "toolstrip-tabs") && contains(htmlText, 'data-view="settings"') && ...
                contains(htmlText, 'id="workspaceRootInput"') && contains(htmlText, 'id="marketplaceRows"') && ...
                contains(htmlText, "Add marketplace") && contains(htmlText, 'id="refreshMarketplacesButton"') && ...
                contains(htmlText, 'id="marketplaceUrlInput"') && ...
                contains(htmlText, 'id="marketplaceReferenceType"') && ...
                contains(htmlText, "Git Credential Manager") && ...
                contains(htmlText, "<th scope=""col"">Branch/tag</th>") && ...
                contains(htmlText, 'id="marketplaceRegistrationStatus"') && ...
                contains(htmlText, 'id="marketplaceConfirmStatus"') && ...
                contains(scriptText, "setMarketplaceRegistrationState") && ...
                contains(scriptText, "setMarketplaceConfirmationState") && ...
                contains(htmlText, 'id="registerMarketplaceModal"') && ...
                ~contains(htmlText, 'id="marketplaceVisibilitySelect"') && ~contains(htmlText, 'id="refreshAllButton"'), ...
                "app must expose cache and app settings in the Settings tab");
            for phrase = ["Settings file:", "mission session(s) ready to resume.", ...
                    "Clear a cache to rebuild that marketplace."]
                testCase.verifyFalse(contains(combinedText, phrase), ...
                    "app must not expose removed text: " + phrase);
            end
            testCase.verifyTrue(contains(htmlText, "<th scope=""col"">Source</th>") && ...
                contains(scriptText, "tableCell(marketplace.SourceUrl)"), ...
                "Marketplace table must show each marketplace source URL as plain text");
            testCase.verifyTrue(contains(scriptText, "marketplaceUpdatesAvailable") && ...
                contains(scriptText, "Update available"), ...
                "app must notify learners when a newer marketplace revision is available");
        end

        function validatesAuthoringWorkspaceAssets(testCase, Root)
            root = string(Root);
            testCase.verifyTrue(isfile(fullfile(root, "src", "startMissionAuthoring.m")), ...
                "missing short authoring workspace entry point");
            testCase.verifyTrue(isfile(fullfile(root, "src", "+interactiveMissions", "startMissionAuthoring.m")), ...
                "missing namespaced authoring workspace entry point");
            verifyAuthorAdapters(testCase, root);
        end

        function validatesIgnoredLocalFolders(testCase, Root)
            root = string(Root);
            gitignoreText = fileread(fullfile(root, ".gitignore"));

            testCase.verifyEmpty(regexp(gitignoreText, "(?m)^\s*progress/\s*$", "once"), ...
                ".gitignore must not ignore progress/");
            testCase.verifyEmpty(regexp(gitignoreText, "(?m)^\s*build/\s*$", "once"), ...
                ".gitignore must not ignore build/");
        end

        function rejectsInternalGitLabUrls(testCase, Root)
            root = string(Root);
            internalGitLabHost = "insidelabs-git.mathworks.com";
            readmeText = lower(string(fileread(fullfile(root, "README.md"))));
            settingsText = lower(string(fileread(fullfile(root, "src", "app", "setting.json"))));

            testCase.verifyFalse(contains(readmeText, internalGitLabHost), ...
                "README must not contain internal GitLab URLs");
            testCase.verifyFalse(contains(settingsText, internalGitLabHost), ...
                "app settings must not contain internal GitLab URLs");
        end
    end
end

function name = parentName(path)
    [~, name] = fileparts(path);
    name = string(name);
end

function blockText = missionTaskBlockText(text, taskStarts, taskEnds, taskIndex)
    if taskIndex < numel(taskStarts)
        blockEnd = taskStarts(taskIndex + 1) - 1;
    else
        blockEnd = strlength(text);
    end

    blockText = regexprep(extractBetween(text, taskEnds(taskIndex) + 1, blockEnd), "\s+", " ");
end

function verifyAuthorAdapters(testCase, root)
    matrix = jsondecode(fileread(fullfile(root, "docs", "agent-support-matrix.json")));
    for agent = reshape(matrix.agents, 1, [])
        testCase.verifyTrue(isfield(agent, "author_adapter_path"), ...
            "agent support matrix must define an author adapter path");
        adapterPath = fullfile(root, string(agent.author_adapter_path));
        testCase.verifyTrue(isfile(adapterPath), ...
            "author adapter is missing: " + string(agent.author_adapter_path));
    end
end
