classdef SafeWorkspaceApisTest < matlab.unittest.TestCase
    %SAFEWORKSPACEAPISTEST Verify public MATLAB APIs used by safe workspaces.

    properties (TestParameter)
        Root = {interactiveMissionsSmoke.defaultRoot()}
    end

    methods (Test)
        function validatesCatalog(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            missions = interactiveMissions.catalog(ContentRoot=fullfile(root, "marketplace", "missions"));
            testCase.verifyGreaterThanOrEqual(height(missions), 1, "catalog must find packaged missions");
            testCase.verifyTrue(any(missions.MissionName == "root-inports-outports"), ...
                "catalog must include root-inports-outports");
        end

        function validatesMarketplaceCatalogAndLaunch(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            workspaceRoot = tempname;
            testCase.addTeardown(@removeFolder, workspaceRoot);

            missions = interactiveMissions.catalog(MarketplaceRoot=fullfile(root, "marketplace"));
            missionIndex = find(missions.MissionName == "root-inports-outports", 1);
            testCase.assertNotEmpty(missionIndex, "catalog must include marketplace missions");
            testCase.verifyEqual(missions.SourceType(missionIndex), "marketplace");
            testCase.verifyEqual(missions.MarketplaceSource(missionIndex), "mathworks-interactive-missions");
            testCase.verifyEqual(missions.TaskIds{missionIndex}(1), "t01", ...
                "catalog task IDs must begin with the first mission task, not a learning outcome");

            info = interactiveMissions.prepareWorkspace( ...
                WorkspaceRoot=workspaceRoot, ...
                MissionName="root-inports-outports", ...
                Mode="practice", ...
                RequireEmpty=true);
            testCase.verifyTrue(isfile(fullfile(info.ContentRoot, "mission.yaml")), ...
                "prepared workspace must copy marketplace mission content");
            testCase.verifyTrue(isfile(fullfile(info.SkillRoot, "references", "advance-organizer.md")), ...
                "prepared workspace must copy the organizer into the portable tutor skill");
            testCase.verifyTrue(isfile(fullfile(info.SkillRoot, "references", "status-reporting.md")), ...
                "prepared workspace must copy status-reporting guidance into the portable tutor skill");
            testCase.verifyTrue(isfile(fullfile(workspaceRoot, "AGENTS.md")), ...
                "prepared workspace must include Generic adapter guidance by default");
        end

        function validatesLaunchCommand(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            command = interactiveMissions.launchCommand( ...
                SafeRoot=fullfile(root, "tmp_safe_workspace"), ...
                MissionName="root-inports-outports", Agent="codex", Shell="powershell");
            testCase.verifyTrue(startsWith(command, "cd "), ...
                "launch command must be a simple cd command");
            testCase.verifyFalse(contains(command, "launch-prompt.md"), ...
                "launch command must not print the generated prompt");
            testCase.verifyFalse(contains(command, "Use learner profile"), ...
                "launch command must not mix shell commands with prompt text");
            verifyNameValueRejected(testCase, @() interactiveMissions.launchCommand( ...
                SafeRoot=fullfile(root, "tmp_safe_workspace"), ...
                MissionName="root-inports-outports", Profile="alice", Agent="codex", Shell="powershell"), ...
                "Profile");

            copilotCommand = interactiveMissions.launchCommand( ...
                SafeRoot=fullfile(root, "tmp_safe_workspace"), ...
                MissionName="root-inports-outports", Agent="copilot", Shell="powershell");
            testCase.verifyTrue(startsWith(copilotCommand, "code "), ...
                "Copilot launch command must open the workspace in VS Code");
        end

        function validatesPrerequisites(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            status = interactiveMissions.prerequisites();
            names = string({status.Name});
            for dependency = ["MATLAB MCP Server", "Agentic Toolboxes", "Terminal-in-MATLAB"]
                testCase.verifyTrue(any(names == dependency), ...
                    "prerequisites must report " + dependency);
            end
        end

        function validatesDefaultWorkspaceFolderNaming(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            defaultRoot = interactiveMissions.internal.defaultSafeRoot();
            testCase.verifyTrue(endsWith(defaultRoot, fullfile("Documents", "MATLAB", "Interactive-Missions")), ...
                "default workspace parent must live under Documents/MATLAB/Interactive-Missions");

            parentRoot = tempname;
            mkdir(parentRoot);
            mkdir(fullfile(parentRoot, "root-inports-outports"));
            mkdir(fullfile(parentRoot, "root-inports-outports_2"));
            testCase.addTeardown(@removeFolder, parentRoot);

            workspaceRoot = interactiveMissions.internal.nextWorkspaceRoot( ...
                "root-inports-outports", ParentRoot=parentRoot);
            testCase.verifyEqual(workspaceRoot, fullfile(parentRoot, "root-inports-outports_3"), ...
                "workspace folder names must use mission-name first, then mission-name_increment");

            generatedRoot = fullfile(parentRoot, "root-inports-outports_3");
            testCase.verifyEqual(interactiveMissions.internal.workspaceBaseRoot(generatedRoot), defaultRoot, ...
                "generated mission folders under temp must normalize to the MATLAB default base");

            nonTemporaryParent = fullfile(root, "build", "workspace-base-test");
            mkdir(nonTemporaryParent);
            testCase.addTeardown(@removeFolder, nonTemporaryParent);
            nonTemporaryGeneratedRoot = fullfile(nonTemporaryParent, "root-inports-outports_2");
            testCase.verifyEqual(interactiveMissions.internal.workspaceBaseRoot(nonTemporaryGeneratedRoot), ...
                string(nonTemporaryParent), ...
                "generated mission folders outside temp must normalize back to their parent base");

            simpleWorkspaceRoot = interactiveMissions.internal.nextWorkspaceRoot( ...
                "agentic-teaching-visualizations", ParentRoot=parentRoot);
            testCase.verifyEqual(simpleWorkspaceRoot, fullfile(parentRoot, "agentic-teaching-visualizations"), ...
                "first workspace folder must use the mission name without an increment");

            mkdir(fullfile(parentRoot, "agentic-paper-to-code-prototype_1"));
            legacySuffixRoot = interactiveMissions.internal.nextWorkspaceRoot( ...
                "agentic-paper-to-code-prototype", ParentRoot=parentRoot);
            testCase.verifyEqual(legacySuffixRoot, fullfile(parentRoot, "agentic-paper-to-code-prototype"), ...
                "first unsuffixed workspace folder must be preferred when only legacy suffixed folders exist");
        end

        function validatesPrepareWorkspaceEmptyFolderRules(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            workspaceRoot = tempname;
            info = interactiveMissions.prepareWorkspace( ...
                WorkspaceRoot=workspaceRoot, ...
                MissionName="root-inports-outports", ...
                Mode="regular", ...
                RequireEmpty=true);
            testCase.addTeardown(@removeFolder, workspaceRoot);
            testCase.verifyTrue(isfile(info.LaunchPromptPath), "regular launch prompt must be created");
            testCase.verifyEqual(info.ProgressPath, fullfile(workspaceRoot, ".interactive-missions", "progress.json"), ...
                "regular progress path must be workspace-local");
            testCase.verifyTrue(isfile(info.ProgressPath), "regular launch must create workspace-local progress");
            progress = jsondecode(fileread(info.ProgressPath));
            testCase.verifyEqual(string(progress.missionName), "root-inports-outports", ...
                "regular progress must include the catalog mission name used by the app");
            testCase.verifyEqual(string(progress.currentStepId), "t01", ...
                "regular progress must start at Task 1");
            testCase.verifyEqual(string(progress.learnerName), "", ...
                "regular progress must start with a blank learner name for Ada to collect");
            manifest = jsondecode(fileread(info.ManifestPath));
            testCase.verifyFalse(isfield(manifest, "learnerName"), ...
                "prepared workspace manifest must not carry learner identity");
            testCase.verifyFalse(isfield(manifest, "profileId"), ...
                "prepared workspace manifest must not carry profile identity");
            testCase.verifyTrue(contains(fileread(info.LaunchPromptPath), "Ada must collect and save"), ...
                "regular launch prompt must delegate display-name collection to Ada");
            verifyNameValueRejected(testCase, @() interactiveMissions.prepareWorkspace( ...
                WorkspaceRoot=tempname, ...
                MissionName="root-inports-outports", ...
                Profile="alice", ...
                Mode="regular", ...
                RequireEmpty=true), ...
                "Profile");

            nonEmptyRoot = tempname;
            mkdir(nonEmptyRoot);
            testCase.addTeardown(@removeFolder, nonEmptyRoot);
            writeText(fullfile(nonEmptyRoot, "existing.txt"), "existing");
            testCase.verifyError(@() interactiveMissions.prepareWorkspace( ...
                WorkspaceRoot=nonEmptyRoot, ...
                MissionName="root-inports-outports", ...
                Mode="practice", ...
                RequireEmpty=true), "InteractiveMissions:WorkspaceNotEmpty");
        end

        function validatesAgentClientAdapters(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            expectedFiles = containers.Map( ...
                ["codex", "claude-code", "gemini-cli", "github-copilot-vscode", "github-copilot-cli", "generic"], ...
                { ...
                ["AGENTS.md", fullfile(".codex", "skills", "mission-tutoring", "SKILL.md")], ...
                ["CLAUDE.md", fullfile(".claude", "commands", "mission-tutoring.md")], ...
                "GEMINI.md", ...
                [fullfile(".github", "copilot-instructions.md"), fullfile(".github", "prompts", "mission-tutoring.prompt.md")], ...
                "COPILOT.md", ...
                ["AGENTS.md", "START_MISSION.md"] ...
                });
            forbiddenFiles = containers.Map( ...
                ["codex", "claude-code", "gemini-cli", "github-copilot-vscode", "github-copilot-cli", "generic"], ...
                { ...
                ["CLAUDE.md", "GEMINI.md", fullfile(".github", "copilot-instructions.md")], ...
                ["AGENTS.md", "GEMINI.md", fullfile(".codex", "skills", "mission-tutoring", "SKILL.md")], ...
                ["AGENTS.md", "CLAUDE.md", fullfile(".codex", "skills", "mission-tutoring", "SKILL.md")], ...
                ["AGENTS.md", "CLAUDE.md", "GEMINI.md", fullfile(".codex", "skills", "mission-tutoring", "SKILL.md")], ...
                ["AGENTS.md", "CLAUDE.md", "GEMINI.md", fullfile(".codex", "skills", "mission-tutoring", "SKILL.md")], ...
                ["CLAUDE.md", "GEMINI.md", fullfile(".codex", "skills", "mission-tutoring", "SKILL.md"), ...
                fullfile(".github", "copilot-instructions.md")] ...
                });

            for agentClient = keys(expectedFiles)
                workspaceRoot = tempname;
                info = interactiveMissions.prepareWorkspace( ...
                    WorkspaceRoot=workspaceRoot, ...
                    MissionName="root-inports-outports", ...
                    Mode="practice", ...
                    RequireEmpty=true, ...
                    AgentClient=string(agentClient{1}));
                testCase.addTeardown(@removeFolder, workspaceRoot);
                testCase.verifyEqual(info.AgentClient, string(agentClient{1}), ...
                    "prepared workspace must report the selected agent client");
                for expectedFile = string(expectedFiles(agentClient{1}))
                    testCase.verifyTrue(isfile(fullfile(workspaceRoot, expectedFile)), ...
                        "missing adapter file: " + expectedFile + " for " + string(agentClient{1}));
                end
                for forbiddenFile = string(forbiddenFiles(agentClient{1}))
                    testCase.verifyFalse(isfile(fullfile(workspaceRoot, forbiddenFile)), ...
                        "workspace should not contain unselected adapter file: " + forbiddenFile);
                end
                if string(agentClient{1}) == "codex"
                    testCase.verifyTrue(isfile(fullfile(workspaceRoot, ".codex", "skills", ...
                        "mission-tutoring", "references", "advance-organizer.md")), ...
                        "Codex workspace must copy the organizer into its local tutor skill");
                end
            end
        end

        function validatesPracticeModeDoesNotPrepareProgress(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            workspaceRoot = tempname;
            info = interactiveMissions.prepareWorkspace( ...
                WorkspaceRoot=workspaceRoot, ...
                MissionName="root-inports-outports", ...
                Mode="practice", ...
                RequireEmpty=true);
            testCase.addTeardown(@removeFolder, workspaceRoot);

            testCase.verifyEqual(info.ProgressPath, "", ...
                "practice mode must not assign a progress path");
            manifest = jsondecode(fileread(info.ManifestPath));
            testCase.verifyEqual(string(manifest.resumableProgressPath), ...
                fullfile(workspaceRoot, ".interactive-missions", "progress.json"), ...
                "practice manifest must declare where progress can be saved after opt-in");
            testCase.verifyFalse(isfolder(fullfile(workspaceRoot, "progress")), ...
                "practice mode must not create progress folders");
            testCase.verifyTrue(contains(fileread(info.LaunchPromptPath), "Practice mode starts progress-free"), ...
                "practice launch prompt must explain progress starts disabled");
            testCase.verifyTrue(contains(fileread(info.LaunchPromptPath), "If the learner asks to save progress"), ...
                "practice launch prompt must explain how to promote the workspace to tracked progress");
        end

        function validatesLegacyProfilePreferencesArePurged(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            settingsPath = fullfile(prefdir(), "InteractiveMissions", "settings.json");
            if isfile(settingsPath)
                originalText = fileread(settingsPath);
                testCase.addTeardown(@writeText, settingsPath, originalText);
            else
                testCase.addTeardown(@deleteFile, settingsPath);
            end

            legacySettings = struct("LastProfile", "alice", "LastWorkspace", string(tempdir()));
            settings = interactiveMissions.preferences("set", Settings=legacySettings);
            testCase.verifyFalse(isfield(settings, "LastProfile"), ...
                "preferences must remove legacy LastProfile on write");
            savedSettings = jsondecode(fileread(settingsPath));
            testCase.verifyFalse(isfield(savedSettings, "LastProfile"), ...
                "persisted preferences must not retain legacy LastProfile");
        end

        function validatesReadOnlyPermissionInPreparedWorkspace(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            readOnlyRoot = tempname;
            readOnlyInfo = interactiveMissions.prepareWorkspace( ...
                WorkspaceRoot=readOnlyRoot, ...
                MissionName="root-inports-outports", ...
                Mode="practice", ...
                RequireEmpty=true, ...
                AgentClient="codex");
            testCase.addTeardown(@removeFolder, readOnlyRoot);

            readOnlyManifest = jsondecode(fileread(readOnlyInfo.ManifestPath));
            testCase.verifyFalse(readOnlyManifest.allowAgentEdits, ...
                "missions must default prepared workspaces to read-only");
            testCase.verifyTrue(contains(fileread(fullfile(readOnlyRoot, "AGENTS.md")), "Agent edits: disabled"), ...
                "adapter instructions must expose read-only mode");
        end

        function validatesMarketplaceRegistrationInput(testCase, Root)
            root = string(Root);
            addSourceFolder(testCase, root);

            testCase.verifyError(@() interactiveMissions.registerMarketplace( ...
                SourceUrl="http://git.example.com/group/marketplace", ...
                ReplaceExisting=false), "InteractiveMissions:InvalidMarketplaceUrl");
        end
    end
end

function addSourceFolder(testCase, root)
    originalPath = path();
    testCase.addTeardown(@path, originalPath);
    addpath(fullfile(root, "src"));
    installMarketplaceFixture(testCase, root);
end

function installMarketplaceFixture(testCase, root)
    cacheBase = fullfile(prefdir(), "InteractiveMissions", "marketplaces");
    if ~isfolder(cacheBase)
        mkdir(cacheBase);
    end

    originalRecords = interactiveMissions.internal.marketplaceRegistry("get");
    fixtureParent = string(tempname(cacheBase));
    fixtureRoot = fullfile(fixtureParent, "content");
    copyfile(fullfile(root, "marketplace"), fixtureRoot);
    record = struct( ...
        "Id", "test-fixture", ...
        "Title", "Test Marketplace", ...
        "SourceUrl", "https://github.com/example/test-marketplace", ...
        "RemoteUrl", "https://github.com/example/test-marketplace", ...
        "ContentVersion", "test", ...
        "MinimumToolboxVersion", "0.1.0", ...
        "CacheRoot", fixtureRoot, ...
        "UpdateStatus", "current", ...
        "UpdateMessage", "Test fixture.", ...
        "LastRefreshedAt", "" ...
        );
    interactiveMissions.internal.marketplaceRegistry("set", Records=record);
    testCase.addTeardown(@restoreMarketplaceRegistry, originalRecords);
    testCase.addTeardown(@removeFolder, fixtureParent);
end

function restoreMarketplaceRegistry(records)
    interactiveMissions.internal.marketplaceRegistry("set", Records=records);
end

function verifyNameValueRejected(testCase, action, rejectedName)
    try
        action();
        testCase.verifyFail("Expected name-value argument to be rejected: " + rejectedName);
    catch exception
        testCase.verifyTrue(contains(string(exception.message), rejectedName), ...
            "error message must identify rejected name-value argument: " + rejectedName);
    end
end

function writeText(path, text)
    fileIdentifier = fopen(path, "w");
    cleanup = onCleanup(@() fclose(fileIdentifier));
    fwrite(fileIdentifier, text);
    clear cleanup
end

function deleteFile(path)
    if isfile(path)
        delete(path);
    end
end

function removeFolder(folder)
    if isfolder(folder)
        rmdir(folder, "s");
    end
end
