classdef ToolboxLayoutTest < matlab.unittest.TestCase
    %TOOLBOXLAYOUTTEST Verify toolbox-first repository layout.

    properties (TestParameter)
        Root = {interactiveMissionsSmoke.defaultRoot()}
    end

    methods (Test)
        function validatesRequiredFiles(testCase, Root)
            root = string(Root);

            testCase.verifyTrue(isfile(fullfile(root, "src", "InteractiveMissions.m")), ...
                "missing app entry point: src/InteractiveMissions.m");
            testCase.verifyTrue(isfile(fullfile(root, "src", "app", "index.html")), ...
                "missing app HTML asset: src/app/index.html");
            testCase.verifyTrue(isfile(fullfile(root, "src", "app", "app.js")), ...
                "missing app JavaScript asset: src/app/app.js");
            testCase.verifyTrue(isfile(fullfile(root, "src", "app", "styles.css")), ...
                "missing app CSS asset: src/app/styles.css");
            testCase.verifyEmpty(dir(fullfile(root, "src", "app", "*-v*.html")), ...
                "app source must have only one HTML file");
            testCase.verifyEmpty(dir(fullfile(root, "src", "app", "*-v*.js")), ...
                "app source must have only one JavaScript file");
            testCase.verifyEmpty(dir(fullfile(root, "src", "app", "*-v*.css")), ...
                "app source must have only one stylesheet");
            testCase.verifyEqual(numel(dir(fullfile(root, "src", "app", "*.html"))), 1, ...
                "app source must have exactly one HTML file");
            testCase.verifyEqual(numel(dir(fullfile(root, "src", "app", "*.js"))), 1, ...
                "app source must have exactly one JavaScript file");
            testCase.verifyEqual(numel(dir(fullfile(root, "src", "app", "*.css"))), 1, ...
                "app source must have exactly one stylesheet");
            for assetName = ["gradcap.svg", "matlab1.svg", "simulink1.svg"]
                testCase.verifyTrue(isfile(fullfile(root, "src", "app", "assets", ...
                    "thumbnails", assetName)), "missing fallback thumbnail: " + assetName);
            end
            testCase.verifyTrue(isfile(fullfile(root, "src", "InteractiveMissions.m")), ...
                "missing Apps Gallery entry point: src/InteractiveMissions.m");
            testCase.verifyTrue(isfile(fullfile(root, "buildfile.m")), ...
                "missing build tool entry point: buildfile.m");
            testCase.verifyTrue(isfile(fullfile(root, "src", "skills", "mission-tutoring", "SKILL.md")), ...
                "missing learner tutor skill");
            testCase.verifyTrue(isfolder(fullfile(root, "src", "adapters")), ...
                "missing runtime adapters");
            testCase.verifyTrue(isfolder(fullfile(root, "src", "author-skills")), ...
                "missing packaged author skills");
            testCase.verifyTrue(isfolder(fullfile(root, "tests")), ...
                "missing test folder");
            testCase.verifyTrue(isfolder(fullfile(root, "marketplace", "missions")), ...
                "missing packaged mission content folder");
            testCase.verifyTrue(isfile(fullfile(root, "marketplace", "manifest.yaml")), ...
                "missing marketplace manifest");
        end

        function rejectsPluginLayoutFiles(testCase, Root)
            root = string(Root);

            testCase.verifyFalse(interactiveMissionsSmoke.hasFiles(fullfile(root, ".claude-plugin")), ...
                "root Claude plugin metadata files must not exist");
            testCase.verifyFalse(interactiveMissionsSmoke.hasFiles(fullfile(root, ".agents", "plugins")), ...
                "root Codex plugin marketplace metadata files must not exist");
            testCase.verifyFalse(interactiveMissionsSmoke.hasFiles(fullfile(root, "plugins")), ...
                "plugin files must not exist in toolbox-first layout");
            testCase.verifyFalse(isfolder(fullfile(root, "resources")), ...
                "old top-level resources folder must not exist");
            testCase.verifyFalse(isfile(fullfile(root, "src", "+interactiveMissions", "importMissionPack.m")), ...
                "single-mission ZIP import API must not exist");
            testCase.verifyFalse(isfile(fullfile(root, "src", "+interactiveMissions", "exportMissionPack.m")), ...
                "single-mission ZIP export API must not exist");
            testCase.verifyFalse(isfile(fullfile(root, "src", "+interactiveMissions", "+internal", ...
                "userMissionLibraryRoot.m")), "user mission library API must not exist");
        end

        function validatesMarketplaceManifest(testCase, Root)
            root = string(Root);
            manifestPath = fullfile(root, "marketplace", "manifest.yaml");
            manifestText = string(fileread(manifestPath));

            for field = ["schema_version", "id", "title", "source_url", ...
                    "content_version", "minimum_toolbox_version", "adapters", "missions"]
                testCase.verifyNotEmpty(regexp(manifestText, "(?m)^" + field + ":", "once"), ...
                    "marketplace manifest missing required field: " + field);
            end
            testCase.verifyNotEmpty(regexp(manifestText, '(?m)^\s+- id:\s*"generic"\s*$', "once"), ...
                "marketplace manifest must include the Generic adapter");
            testCase.verifyTrue(isfile(fullfile(root, "src", "adapters", "generic", "adapter.yaml")), ...
                "src must include a Generic adapter manifest");
        end

        function validatesPackagingMetadata(testCase, Root)
            root = string(Root);
            buildfilePath = fullfile(root, "buildfile.m");

            testCase.assertTrue(isfile(buildfilePath), "missing build tool entry point");
            buildfileText = fileread(buildfilePath);
            for phrase = ["ToolboxOptions", "AppGalleryFiles", "ProductDependencies"]
                testCase.verifyTrue(contains(buildfileText, phrase), ...
                    "buildfile.m must configure " + phrase);
            end
            testCase.verifyTrue(contains(buildfileText, "sourceRoot") && ...
                contains(buildfileText, "docsRoot") && ...
                contains(buildfileText, "opts.ToolboxFiles"), ...
                "buildfile.m must package learner and author documentation with the toolbox");

            for phrase = ["buildplan", "packageTask", "buildToolbox"]
                testCase.verifyTrue(contains(buildfileText, phrase), ...
                    "buildfile.m must configure " + phrase);
            end

            testCase.verifyTrue(contains(buildfileText, "8c2c47ce-1c6a-4a53-94d6-8e6ec37e7b92"), ...
                "buildfile.m must reference the Interactive Missions toolbox ID");
        end

        function validatesPathHelpers(testCase, Root)
            root = string(Root);
            testCase.verifyTrue(interactiveMissions.internal.isAbsolutePath(root), ...
                "repository root must be recognized as an absolute path");
            testCase.verifyTrue(interactiveMissions.internal.isPathWithin( ...
                fullfile(root, "src"), root), ...
                "a child folder must be recognized as inside its root");
            testCase.verifyFalse(interactiveMissions.internal.isPathWithin( ...
                root + "-other", root), ...
                "a sibling with the same prefix must not be treated as a child");
        end
    end
end
